name: 'Apply Prod Infrastructure'

on:
  push:
    branches: [ main ]
    paths: 
       - 'deploy-infra/prod/**'
  workflow_dispatch: {}

jobs:    
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deploy-infra/prod
  
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate 
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan 
        id: plan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_aws_region: "us-east-1"
        run: terraform plan -refresh=false -no-color -parallelism=1